name: Bug Report
description: Report an issue with this project.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the issue you are facing.
      placeholder: Describe your issue...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Describe the steps we should take to reproduce this issue.
      placeholder: Reproduction steps...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe how the software should behave.
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Platform & Version Info
      description: Tell us information about the platform and version you are using.
      placeholder: Platform information...
      value: |
        Platform: Windows/Mac OS
        OS Version: eg, 26.1
        Ringer Version: eg, 5.2.1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any other information you would like to tell us?
      placeholder: Extra information...
    validations:
      required: false
