# Tells the server what ip and port to host on
Host: localhost
Port: 8000

# Tells the server the path to the logs folder 
Path-To-Logs: src/logs

# Tells the server where to look for the database
Path-To-Database: src/account.db